import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";

// const inter = Inter({ subsets: ["latin"] });

const polysansTrial = localFont({
  src: [
    {
      path: "../../public/PolySans-trial/Standard/PolySansTrial-Neutral.otf",
      weight: "400",
    },
    {
      path: "../../public/PolySans-trial/Standard/PolySansTrial-Slim.otf",
      weight: "300",
    },
    {
      path: "../../public/PolySans-trial/Standard/PolySansTrial-Median.otf",
      weight: "500",
    },
    {
      path: "../../public/PolySans-trial/Standard/PolySansTrial-Bulky.otf",
      weight: "700",
    },
  ],
});

export const metadata: Metadata = {
  title: "EzeeMedia: Groundbreaking PR Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={polysansTrial.className}>
        {children}
      </body>
    </html>
  );
}
